name: Build and deploy Laravel app to Azure Web App - femaza

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, mysql

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare deployment zip
        run: |
          rm -rf vendor node_modules
          zip -r release.zip . -x "node_modules/*" ".git/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3082BA4D338041638CA79E8C8EE304DE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D03A633EA026430F8F148D5E58E893CD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_07A652354E044B548C474851EA26C7B1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'femaza'
          slot-name: 'Production'
          package: .

      - name: Run artisan commands post-deploy (via Kudu API)
        run: |
          curl -s -u ${{ secrets.AZURE_DEPLOY_USER }}:${{ secrets.AZURE_DEPLOY_PASS }} \
          -X POST "https://femaza.scm.azurewebsites.net/api/command" \
          -d "command=cd site/wwwroot && php artisan key:generate && php artisan migrate --force && php artisan storage:link"
